// Arabic translations, keyed by the exact English text shown on the page.
// Anything missing here simply stays in English, so names of tools, languages
// and libraries (Python, XGBoost, Raspberry Pi…) are left out on purpose.

export const AR: Record<string, string> = {
  // ---------- top bar, buttons, labels ----------
  "PRO VIEW": "الوضع المهني",
  "Arcade view": "وضع الأركيد",
  PLAYER: "اللاعبة",
  BONUS: "المكافأة",
  QUESTS: "المشاريع",
  TROPHIES: "الجوائز",
  ACADEMY: "الدراسة",
  SKILLS: "المهارات",
  PARTY: "الفرق",
  CV: "السيرة الذاتية",
  "CHARACTER SHEET": "السيرة الذاتية",
  "MY FULL CV": "سيرتي الذاتية كاملة",
  "Education, research, patent, awards, leadership and activities, all in one place.": "التعليم والأبحاث وبراءة الاختراع والجوائز والقيادة والأنشطة، في مكان واحد.",
  "View CV": "عرض السيرة الذاتية",
  "View my CV": "عرض سيرتي الذاتية",
  "Download PDF": "تحميل PDF",
  SAVE: "الحفظ",
  About: "نبذة عني",
  Projects: "المشاريع",
  Recognition: "الجوائز والتكريم",
  Education: "التعليم",
  Skills: "المهارات",
  Leadership: "القيادة",
  Contact: "تواصل",
  NELMKT: "NELMKT",
  "Nelly Almaktoum": "نيللي المكتوم",
  "Photo of Nelly Almaktoum": "صورة نيللي المكتوم",
  "Researcher & Innovator": "باحثة ومبتكرة",
  STAGE: "المرحلة",
  "PLAYER SELECT": "اختر شخصيتك",
  "BONUS STAGE - LANGUAGE RUSH": "مرحلة المكافأة - سباق اللغات",
  "QUEST LOG": "سجل المشاريع",
  "Research & projects": "الأبحاث والمشاريع",
  "TROPHY ROOM": "قاعة الجوائز",
  "ACADEMY & SIDE QUESTS": "الدراسة والمهام الجانبية",
  "Education & activities": "التعليم والأنشطة",
  "SKILL TREE": "شجرة المهارات",
  "Technical skills": "المهارات التقنية",
  "PARTY & GUILDS": "الفرق والأندية",
  "Leadership & community": "القيادة والمجتمع",
  "SAVE POINT": "نقطة الحفظ",
  "Get in touch": "تواصل معي",
  "PLAY BONUS STAGE": "ابدأ مرحلة المكافأة",
  NELLY: "نيللي",
  "FOCUS AREAS": "مجالات اهتمامي",
  OPEN: "فتح",
  "View project": "عرض المشروع",
  "OBJECTIVES CLEARED": "ما أنجزته",
  Highlights: "أبرز النتائج",
  LOOT: "الغنائم",
  Links: "روابط",
  "Source on GitHub": "الكود المصدري على GitHub",
  "ACHIEVEMENT UNLOCKED": "إنجاز جديد",
  "ACHIEVEMENT UNLOCKED - LEGENDARY": "إنجاز أسطوري",
  Patent: "براءة اختراع",
  Distinction: "تميّز",
  Award: "جائزة",
  "SIDE QUESTS CLEARED": "مهام جانبية أنجزتها",
  "Programs & certificates": "برامج وشهادات",
  LANGUAGES: "لغات البرمجة",
  MAIN: "أساسية",
  WORKING: "متوسطة",
  "Main language": "لغة أساسية",
  "Working knowledge": "معرفة متوسطة",
  "The languages I program in, as collectibles. Jump to collect each one and avoid the bugs.": "لغات البرمجة التي أستخدمها، على شكل جوائز تجمعها. اقفز لتجمع كل لغة وتفادَ الأخطاء البرمجية.",
  "ALL LANGUAGES UNLOCKED": "جمعتَ كل اللغات!",
  Locked: "مقفلة",
  "OPEN TO RESEARCH COLLABORATION": "أرحّب بالتعاون البحثي",
  "The quickest way to reach me is LinkedIn or email. I work in Arabic and English.": "أسرع طريقة للتواصل معي عبر LinkedIn أو البريد الإلكتروني، وأتحدث العربية والإنجليزية.",
  "THANKS FOR PLAYING!": "شكرًا على اللعب!",
  "© 2026 Nelly Almaktoum - Built with Next.js, TypeScript, HTML & CSS": "© 2026 نيللي المكتوم - بُني باستخدام Next.js وTypeScript وHTML وCSS",

  // ---------- profile ----------
  "FCIT Student @ KAU - Waed ’26 - IEEE ’25 - UNCCD COP16 ’24 - Mawhiba Alumna":
    "طالبة في كلية الحاسبات وتقنية المعلومات بجامعة الملك عبدالعزيز - واعد 2026 - IEEE 2025 - UNCCD COP16 2024 - خريجة موهبة",
  "Undergraduate researcher and developer working across software, hardware, data and AI/ML.": "باحثة ومطوّرة جامعية، أعمل بين البرمجيات والعتاد والبيانات والذكاء الاصطناعي/تعلم الآلة.",
  "I'm a computer science student at King Abdulaziz University who loves solving problems with code and hardware, from machine learning models and full-stack web apps to Aykah, a solar-powered smart waste bin I designed, built and prototyped end to end.": "أدرس علوم الحاسب في جامعة الملك عبدالعزيز، وأستمتع بحل المشكلات بالبرمجة والعتاد: من نماذج تعلّم الآلة وتطبيقات الويب المتكاملة، إلى «آيكة»، حاوية النفايات الذكية العاملة بالطاقة الشمسية التي صممتها وبنيتها بنفسي من الفكرة حتى النموذج الأولي.",
  "My research connects computing with real-world systems: reproducible ML pipelines, satellite data and IoT, from measuring what urban greening really does in Wahaj to catching pipeline leaks in real time with Maeen. I'm aiming for a Ph.D. and a career in academia. My projects are in the Quest Log below.": "تجمع أبحاثي بين الحوسبة والعالم الحقيقي: مسارات تعلّم آلة قابلة للتكرار، وبيانات الأقمار الصناعية، وإنترنت الأشياء، من قياس الأثر الحقيقي للتشجير الحضري في «وهاج» إلى رصد تسريبات الأنابيب لحظيًا في «مَعين». هدفي الدكتوراه ومسيرة في المجال الأكاديمي، وستجد مشاريعي في سجل المشاريع بالأسفل.",
  "My research connects computing with real-world systems: reproducible ML pipelines, satellite data and IoT, from measuring what urban greening really does in Wahaj to catching pipeline leaks in real time with Maeen. I'm aiming for a Ph.D. and a career in academia. You'll find my work under Research & projects below.": "تجمع أبحاثي بين الحوسبة والعالم الحقيقي: مسارات تعلّم آلة قابلة للتكرار، وبيانات الأقمار الصناعية، وإنترنت الأشياء، من قياس الأثر الحقيقي للتشجير الحضري في «وهاج» إلى رصد تسريبات الأنابيب لحظيًا في «مَعين». هدفي الدكتوراه ومسيرة في المجال الأكاديمي، وستجد أعمالي في قسم الأبحاث والمشاريع أدناه.",
  "I'm also an artist, which probably explains why this site looks the way it does.": "وأنا فنانة أيضًا، ولعل هذا ما يفسّر شكل هذا الموقع.",
  "Youngest UN-certified Saudi researcher": "أصغر باحثة سعودية معتمدة من الأمم المتحدة",
  "6 national & international recognitions - 3 national & international awards": "6 تكريمات و3 جوائز على المستويين الوطني والدولي",
  CLASS: "الدور",
  GUILD: "الجامعة",
  BASE: "المدينة",
  LANGS: "اللغات",
  "MAIN QUEST": "الهدف الأكبر",
  "SIDE QUEST": "هواياتي",
  Role: "الدور",
  University: "الجامعة",
  Location: "المدينة",
  Languages: "اللغات",
  Goal: "الهدف",
  "Outside research": "اهتمامات أخرى",
  "Researcher - Developer - ML Engineer": "باحثة - مطوّرة - مهندسة تعلّم آلة",
  "KAU - BS Computer Science - Waed track": "جامعة الملك عبدالعزيز - بكالوريوس علوم الحاسب - برنامج واعد",
  "Jeddah, Saudi Arabia": "جدة، السعودية",
  "Arabic - English": "العربية والإنجليزية",
  "Ph.D. → academia": "الدكتوراه ثم العمل الأكاديمي",
  "Design & painting": "التصميم والرسم",
  "AI/ML engineering": "هندسة الذكاء الاصطناعي/تعلم الآلة",
  "Full-stack web development": "تطوير الويب المتكامل",
  "IoT & embedded systems": "إنترنت الأشياء والأنظمة المدمجة",
  "Remote sensing": "الاستشعار عن بُعد",
  "Sustainable technology": "التقنيات المستدامة",

  // ---------- quests ----------
  Wahaj: "وهاج",
  Maeen: "مَعين",
  "QUEST COMPLETE - OCT 2026 - PROTOTYPE READY": "مهمة مكتملة - أكتوبر 2026 - النموذج الأولي جاهز",
  "Oct 2026 - Prototype complete": "أكتوبر 2026 - نموذج أولي مكتمل",
  "Real-time detection, location and explanation of leaks and water-quality problems in water pipelines, turning in-pipe sensor streams into what is wrong, where, how serious, why and what to do.":
    "رصد التسريبات ومشكلات جودة المياه في خطوط الأنابيب وتحديد مواقعها وتفسيرها لحظيًا، بتحويل قراءات الحساسات داخل الأنابيب إلى إجابات واضحة: ما المشكلة، وأين، وما مدى خطورتها، ولماذا، وما الذي ينبغي فعله.",
  "Physics-aware features plus gradient boosting: 94.1% fault-type accuracy across 6 classes with 0.3% false alarms on unseen scenarios, against 78.5% for classic threshold rules":
    "خصائص مبنية على فيزياء الجريان مع نماذج التعزيز التدرّجي: دقة 94.1% في تحديد نوع العطل بين 6 فئات، ونسبة إنذارات خاطئة 0.3% على سيناريوهات لم يرها النموذج، مقابل 78.5% لقواعد العتبات التقليدية",
  "Locates faults to the right pair of devices 99.9% of the time, within about 110 m on a 5 km line, with a 5-minute median detection delay for leaks":
    "يحدد موقع العطل بين الجهازين الصحيحين بنسبة 99.9%، وبدقة تقارب 110 أمتار على خط طوله 5 كم، ويرصد التسريب خلال 5 دقائق في المتوسط",
  "Working prototype, trained and stress-tested on a physics-based pipeline simulator with randomised leaks, blockages, contamination, corrosion and sensor faults": "نموذج أولي جاهز ويعمل، دُرّب واختُبر على محاكٍ فيزيائي لخط الأنابيب يولّد تسريبات وانسدادات وتلوثًا وتآكلًا وأعطال حساسات متنوعة",
  "FastAPI service with an Arabic/English dashboard, plain-language evidence for every alert, a model registry and a CI quality gate":
    "خدمة FastAPI مع لوحة متابعة بالعربية والإنجليزية، وتفسير واضح لكل إنذار، وسجل للنماذج، وبوابة جودة آلية",
  "Evaluation report": "تقرير التقييم",
  "Anomaly detection": "رصد الحالات الشاذة",
  "REST APIs": "واجهات REST البرمجية",
  "Explainable AI": "الذكاء الاصطناعي القابل للتفسير",
  "MLOps & model registry": "MLOps وسجل النماذج",
  "Drift monitoring": "مراقبة انحراف البيانات",
  "Physics-based simulation": "المحاكاة الفيزيائية",
  Aykah: "آيكة",
  "MAIN QUEST - JUN–OCT 2026 - RELEASED": "المهمة الرئيسية - يونيو – أكتوبر 2026 - منشور",
  "Jun–Oct 2026 - Released": "يونيو – أكتوبر 2026 - منشور",
  "QUEST COMPLETE - OCT 2024–MAR 2025 - PATENTED - MULTI-AWARD": "مهمة مكتملة - أكتوبر 2024 – مارس 2025 - براءة اختراع - عدة جوائز",
  "Oct 2024–Mar 2025 - Patented - Multiple awards": "أكتوبر 2024 – مارس 2025 - براءة اختراع - عدة جوائز",
  "A reproducible ML Python and Google Earth Engine framework for evaluating urban greening–energy trade-offs in desalination-dependent cities, with Jeddah as the case study.": "إطار عمل مفتوح وقابل للتكرار، مبني بـ Python وGoogle Earth Engine وتعلّم الآلة، يقيس أثر التشجير الحضري على الحرارة واستهلاك الطاقة في المدن التي تعتمد على تحلية المياه، وجدة نموذجًا.",
  "XGBoost land surface temperature model on Landsat 8, spatial cross-validation R² 0.795 on 19,650 cells, benchmarked against random forest, gradient boosting and linear regression": "نموذج XGBoost يتنبأ بحرارة سطح الأرض من صور Landsat 8، بدقة R² = 0.795 في تحقق مكاني على 19,650 خلية، مقارنةً بالغابة العشوائية والتعزيز التدرّجي والانحدار الخطي",
  "Matched-contrast benchmark: −1.18 °C per greened pixel outside the built-up area, stress-tested with emissivity re-retrieval, alternative NDVI thresholds and a thermal-footprint simulation": "كل بكسل مُشجَّر خارج المناطق العمرانية يخفض الحرارة 1.18 °م، وصمدت النتيجة أمام اختبارات متعددة: إعادة حساب الانبعاثية، وعتبات NDVI مختلفة، ومحاكاة للأثر الحراري",
  "Counterfactual gates that test whether predicted greening effects hold up, and report where they do not": "اختبارات تتحقق مما إذا كانت آثار التشجير المتوقعة حقيقية، وتوضح بصراحة أين لا تصمد",
  "NEGI index plus a water–energy ledger: each degree of cooling carries ~2.9–5.3 MWh/yr of desalination energy": "مؤشر NEGI مع حساب للمياه والطاقة: كل درجة تبريد تكلّف قرابة 2.9 – 5.3 ميغاواط ساعة سنويًا من طاقة التحلية",
  "Zenodo DOI 10.5281/zenodo.23168529": "DOI على Zenodo: 10.5281/zenodo.23168529",
  "Latest release": "أحدث إصدار",
  "Spatial statistics": "الإحصاء المكاني",
  "A cost-effective, solar-powered IoT smart bin, taken from scientific research on a Sustainable Development Goal problem through to a working prototype and a business concept.": "حاوية نفايات ذكية منخفضة التكلفة تعمل بالطاقة الشمسية وإنترنت الأشياء، بدأت ببحث علمي حول أحد أهداف التنمية المستدامة وانتهت بنموذج أولي يعمل وفكرة مشروع تجاري.",
  "Built as my graduation project at Dar Al Fikr Schools: SDG research, a functional prototype and a business concept with its own identity": "مشروع تخرجي في مدارس دار الفكر: بحث في أهداف التنمية المستدامة، ونموذج أولي يعمل، وفكرة تجارية بهوية مستقلة",
  "Raspberry Pi with ultrasonic fill sensing, LCD interface, LED status indicators and air filtration": "Raspberry Pi مع حساس بالموجات فوق الصوتية لقياس الامتلاء، وشاشة LCD، ومؤشرات LED، ونظام لتنقية الهواء",
  "Community survey of 222 participants on waste disposal behaviour and acceptance of smart waste technology": "استبيان مجتمعي شارك فيه 222 شخصًا حول عادات التخلص من النفايات ومدى تقبّل الحلول الذكية",
  "Young Researchers Award (Modern Technologies) at UNCCD COP16": "جائزة الباحثين الشباب (التقنيات الحديثة) في مؤتمر الأمم المتحدة UNCCD COP16",
  "Patented: the Aykah smart waste management system is protected by a patent": "حاصلة على براءة اختراع لنظام آيكة الذكي لإدارة النفايات",
  "Featured in the Saudi Gazette": "قصتي في صحيفة Saudi Gazette",
  "Solar power": "الطاقة الشمسية",
  "Rapid prototyping": "النمذجة السريعة",

  // ---------- trophies ----------
  PATENT: "براءة اختراع",
  "SEP 2026": "سبتمبر 2026",
  "JUN 2026": "يونيو 2026",
  "JAN 2025": "يناير 2025",
  "DEC 2024": "ديسمبر 2024",
  "FEB 2022": "فبراير 2022",
  NATIONAL: "وطني",
  "Patent - Aykah Smart Bin": "براءة اختراع - حاوية آيكة الذكية",
  "Patent for Aykah, the solar-powered IoT smart waste management system": "براءة اختراع لآيكة، نظام ذكي لإدارة النفايات يعمل بالطاقة الشمسية وإنترنت الأشياء",
  "Inventor: Nelly Almaktoum": "المخترعة: نيللي المكتوم",
  "Featured - Saudi Gazette": "قصة صحفية - Saudi Gazette",
  "Feature story on my journey from curiosity to the award-winning Aykah smart bin": "مقال عن رحلتي من الفضول إلى ابتكار حاوية آيكة الحائزة على جوائز",
  "Saudi Gazette": "Saudi Gazette",
  "Certificate of Appreciation": "شهادة شكر وتقدير",
  "For distinguished participation in local and international competitions": "تقديرًا لمشاركتي المتميزة في المسابقات المحلية والدولية",
  "King Abdulaziz University": "جامعة الملك عبدالعزيز",
  "Academic Excellence Award 2025–2026": "جائزة التفوق الأكاديمي 2025 – 2026",
  "GPA of 4.5 or higher across two consecutive semesters": "معدل 4.5 فأعلى لفصلين دراسيين متتاليين",
  "IEEE Ideation Competition": "مسابقة IEEE للأفكار الإبداعية",
  "Presenter & team lead at the 22nd International Learning and Technology Conference (Effat University): a top-ranked paper at the Human Machine Fusion exhibition, leading a team of five": "قدّمتُ وقدتُ فريقًا من خمسة أعضاء في المؤتمر الدولي الثاني والعشرين للتعلم والتقنية بجامعة عفت، ونالت ورقتنا أحد أعلى التقييمات في معرض اندماج الإنسان والآلة",
  "Young Researchers Award - Modern Technologies": "جائزة الباحثين الشباب - التقنيات الحديثة",
  "Selected by an international panel and received at 16, making me the youngest UN-certified Saudi researcher (youngest of 209 researchers and professors from 36 countries)": "اختارتني لجنة دولية ونلت الجائزة في السادسة عشرة، لأصبح أصغر باحثة سعودية معتمدة من الأمم المتحدة، والأصغر بين 209 باحثين وأساتذة من 36 دولة",
  "United Nations Convention to Combat Desertification (UNCCD COP16)": "اتفاقية الأمم المتحدة لمكافحة التصحر (COP16)",
  "National Recognition - NCM": "تكريم وطني - المركز الوطني للأرصاد",
  "Official recognition of Aykah among the selected Young Researchers at UNCCD COP16": "تكريم رسمي لمشروع آيكة ضمن الباحثين الشباب المختارين في COP16",
  "National Center for Meteorology (NCM)": "المركز الوطني للأرصاد",
  "National Recognition - MEWA": "تكريم وطني - وزارة البيئة",
  "National recognition for the Aykah smart bin": "تكريم وطني لحاوية آيكة الذكية",
  "Ministry of Environment, Water and Agriculture (MEWA)": "وزارة البيئة والمياه والزراعة",
  "National Mathematics Olympiad - Final Stage": "أولمبياد الرياضيات الوطني - المرحلة النهائية",
  "Representing the Western Region in the competition’s fourth edition": "مثّلت المنطقة الغربية في النسخة الرابعة من المسابقة",
  "Ministry of Education, Saudi Arabia": "وزارة التعليم",

  // ---------- skills ----------
  "Front end": "الواجهة الأمامية",
  "Back end": "الواجهة الخلفية",
  Tools: "الأدوات",
  "UI & communication": "الواجهات والتواصل",
  "ML engineering": "هندسة تعلّم الآلة",
  Data: "البيانات",
  Hardware: "العتاد",
  "UI prototyping": "نمذجة الواجهات",
  "Public speaking": "الإلقاء",
  "Scientific presentation": "العروض العلمية",
  "Model training & benchmarking": "تدريب النماذج وتقييمها",
  "Random forest & gradient boosting": "الغابة العشوائية والتعزيز التدرّجي",
  "Spatial cross-validation": "التحقق المتقاطع المكاني",
  "Counterfactual testing": "اختبارات السيناريوهات البديلة",
  "Reproducible ML pipelines": "مسارات تعلّم آلة قابلة للتكرار",
  "Embedded systems": "الأنظمة المدمجة",
  "Ultrasonic sensors": "حساسات الموجات فوق الصوتية",
  "LCD & LED interfaces": "واجهات LCD وLED",
  "Solar power systems": "أنظمة الطاقة الشمسية",
  "IoT prototyping": "نمذجة إنترنت الأشياء",
  "Skeleton prototyping": "النماذج الهيكلية",

  // ---------- party ----------
  "Technical Team Lead": "قائد الفريق التقني",
  "Waed Students Community, King Abdulaziz University": "مجتمع طلاب واعد، جامعة الملك عبدالعزيز",
  "Sep 2026 – now": "سبتمبر 2026 – الآن",
  "Tech Department Member": "عضو في القسم التقني",
  "IEEE, 2027 term": "IEEE، دورة 2027",
  "Oct 2026 – now": "أكتوبر 2026 – الآن",
  "Programming Club, 2027 term": "نادي البرمجة، دورة 2027",
  "CM Experience Member": "عضو في فريق تجربة المجتمع",
  "Google Developer Groups, KAU": "مجموعات مطوري Google، جامعة الملك عبدالعزيز",
  "Organizer & Event Coordinator": "منظِّمة ومنسّقة فعاليات",
  "English Language Olympiad (ELO), KAU": "أولمبياد اللغة الإنجليزية (ELO)، جامعة الملك عبدالعزيز",
  "Oct 2026": "أكتوبر 2026",
  "Project Coordinator, Talks X": "منسّقة مشروع Talks X",
  "Engineering Day 2027, KAU": "يوم الهندسة 2027، جامعة الملك عبدالعزيز",
  "Layout & Design Specialist": "مختصة التنسيق والتصميم",
  "Engineering Day 2027 Planning Department": "لجنة التخطيط ليوم الهندسة 2027",
  "Aug 2026 – now": "أغسطس 2026 – الآن",
  Member: "عضو",
  "Scientific Research Club, KAU": "نادي البحث العلمي، جامعة الملك عبدالعزيز",
  Coordinator: "منسّقة",
  "Annual Waed Workshop 2027": "ورشة واعد السنوية 2027",
  "Aug – Sep 2026": "أغسطس – سبتمبر 2026",
  "Intellectual & Electronics Sports Club, KAU": "نادي الرياضات الذهنية والإلكترونية، جامعة الملك عبدالعزيز",
  "Oct 2025 – Jun 2026": "أكتوبر 2025 – يونيو 2026",
  "Mawhiba Alumna": "خريجة موهبة",
  "Mawhiba: STEM enrichment classes for gifted students, 2022–2025": "موهبة: برامج إثرائية في العلوم والتقنية للطلبة الموهوبين، 2022 – 2025",
  "Jun 2025 – now": "يونيو 2025 – الآن",

  // ---------- academy ----------
  "BS, Computer Science - FCIT": "بكالوريوس علوم الحاسب - كلية الحاسبات وتقنية المعلومات",
  "2025 – 2030": "2025 – 2030",
  "Waed: Distinctive Excellence track for gifted students": "واعد للتميز النوعي (المواهب الخاصة)",
  "Dar Al Fikr Schools": "مدارس دار الفكر",
  "American High School Diploma": "شهادة الثانوية الأمريكية",
  "2022 – 2025": "2022 – 2025",
  "Mawhiba Alumna: King Abdulaziz & His Companions Foundation for Giftedness & Creativity":
    "خريجة موهبة: مؤسسة الملك عبدالعزيز ورجاله للموهبة والإبداع",
  "Miyahthon 2027": "مياهثون 2027",
  "Saudi Water Authority": "الهيئة السعودية للمياه",
  "IECE 2026 - International Engineering Conference": "المؤتمر الهندسي الدولي IECE 2026",
  "Saudi Council of Engineers": "الهيئة السعودية للمهندسين",
  "2nd Conference on Sustainability and Quality of Life - Research paper": "المؤتمر الثاني للاستدامة وجودة الحياة - ورقة بحثية",
  "Dec 2026": "ديسمبر 2026",
  "Hackathon Al Hareeq": "هاكاثون الحريق",
  "Ministry of Environment, Water & Agriculture": "وزارة البيئة والمياه والزراعة",
  "Dec 2025": "ديسمبر 2025",
  "Consulting Championship 2025": "بطولة الاستشارات 2025",
  Aramco: "أرامكو",
  "The 2nd Scientific Forum": "الملتقى العلمي الثاني",
  "Nov 2025": "نوفمبر 2025",
  "Organizing Waed’s Annual Introductory Meeting & Workshop": "تنظيم اللقاء التعريفي والورشة السنوية لمجتمع واعد",
  "Sep 2026": "سبتمبر 2026",

  TOP: "للأعلى",
  // game (drawn on the canvas)
  SCORE: "النقاط",
  BEST: "الأفضل",
  "OUCH! A BUG!": "آخ! خطأ برمجي!",
  "LANGUAGE RUSH": "سباق اللغات",
  "COLLECT THE LANGUAGE GEMS - DODGE THE BUGS": "اجمع جواهر اللغات - وتفادَ الأخطاء البرمجية",
  "TAP OR PRESS SPACE TO START": "المس الشاشة أو اضغط المسافة للبدء",
  "GAME OVER": "انتهت اللعبة",
  "TAP OR PRESS SPACE TO RETRY": "المس الشاشة أو اضغط المسافة للمحاولة مجددًا",
  "psst… decode me": "بسست… فك شيفرتي",
  "Decoded message: ابقَ فضوليًا. Click to encode again.": "الرسالة بعد فك الشيفرة: ابقَ فضوليًا. انقر لإخفائها مجددًا.",
  "Binary-encoded secret message. Click to decode.": "رسالة سرية مشفّرة بالنظام الثنائي. انقر لفك شيفرتها.",
  "SPACE / ↑ / TAP = JUMP": "المسافة / ↑ / لمسة = قفزة",
  "Click the screen, then press SPACE or tap to play": "انقر على اللعبة، ثم اضغط المسافة أو المس الشاشة للعب",

  // ---------- contact labels ----------
  Email: "البريد الإلكتروني",
};
